### PR TITLE
chore: initialized and configured project

### PR DESCRIPTION
**Pull request by KumailB**
Hey team,

I initialized and configured the project using a nextJS template that I found online. Please review the changes and let me know if there are any issues.

### CODE REVIEW

**Comment by KumailB** [comment]
Still have to add aws amplify integration

**Comment by KumailB** [comment]
Re-opening PR, will add aws amplify integration after merging

**Review by aidennguyen22 — APPROVED** [review]
This looks good

**Review by rmz190000 — APPROVED** [review]
Everything looks good. The layout and the configurations of the files seem neat and ordered.

**Review by AbbySZ — APPROVED** [review]
Looks good

**Review by aidennguyen22 — APPROVED** [review]

**Review by aidennguyen22 — APPROVED** [review]

**Review by wasif-siddiqui — APPROVED** [review]

**Comment by KumailB** [comment]
Repo moved to https://github.com/OtRL-Reputation-Index/otrl-referral

**Pull request closed without merging**
